name: 🚀 Flutter Web Multi-Branch Deploy

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🛠 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: 📦 Install dependencies
        run: flutter pub get

      # 🔥 Dynamic base-href
      - name: 🌐 Build Web
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            flutter build web --release --base-href "/animation/"
          else
            flutter build web --release --base-href "/animation/dev/"
          fi

      # 🔥 Deploy different folders
      - name: 🚀 Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          destination_dir: ${{ github.ref_name }}